# Generated by Django 3.0.6 on 2020-05-30 12:27

import blog.custom_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_auto_20200526_1714"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, default="", storage=blog.custom_storage.PublicImageStorage, upload_to="post-img/%Y/%m/%d"
            ),
        ),
    ]
